name: Deploy Development Build

on:
    push:
        branches: [development]

jobs:
    deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3.0.2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build
            - name: FTP-Deploy-Action
              uses: SamKirkland/FTP-Deploy-Action@4.3.2
              with:
                  local-dir: ./dist/
                  protocol: ${{ secrets.FTP_PROTOCOL }}
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: ${{ secrets.FTP_SERVER_DIR }}
